name = "url-un"
main = "index.ts"
compatibility_date = "2023-05-19"

# [env.production]
# MY_VARIABLE = "production_value"

# [env.staging]
# MY_VARIABLE = "staging_value"

# [env.shared]
# SHARED_VARIABLE = "shared_value"
