name: Lint Code Base

on: push

jobs:
  super-lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        - uses: actions/checkout@v3
        - uses: bahmutov/npm-install@v1
        - run: npm run format
        - run: git status

 