name: Deploy master on push
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: wrangler publish
        uses: cloudflare/wrangler-action@2.0.0